base_url = "https://jieiku.github.io/abridge-demo/"
title = "abridge - Zola Theme"
description = "abridge is a fast and lightweight Zola theme using semantic html, abridge.css class-light CSS, and No JS."
default_language = "en"
#theme = "abridge"

output_dir = "public"
compile_sass = true
build_search_index = true
minify_html = false
generate_feed = true
feed_filename = "atom.xml"
#ignored_content = ["*.{graphml,xlsx}", "temp.*"]
#hard_link_static = false # set to true to hard link instead of copying, useful for very large files.
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_code = true
highlight_theme = "material-dark" # OneHalfDark, material-dark, ayu-dark, Midnight.dark
#highlight_theme = "css" # use css classes - https://www.getzola.org/documentation/content/syntax-highlighting/#inline-vs-classed-highlighting
render_emoji = false
external_links_target_blank = true # rel="noopener"
external_links_no_follow = false   # rel="nofollow"
external_links_no_referrer = false # rel="noreferrer"
smart_punctuation = false          # `...` to `…`, `"quote"` to `“curly”` etc

[extra]
language_code = "en-US"
author = "Your Name"
author_show = true # displays the author name on line with date, tags, categories
readtime = true # displays the read time on line with date, tags, categories
readtime_string = "min" # read time indication eg "min": - 1 min  "min read": - 1 min read
recent = true
recent_items = 9
footer_credit = true

textlogo = '<font color="#f90">A</font>bridge'
sitedesc = false # enables or disables the display of the site description below the logo.
#copyright_start_year = 2019  # optional
#copyright_end_year = 2020  # optional, recommend leaving unset, zola build will set this to current year by default
menu = [
    {url = "/", name = "Home", slash = true},
    {url = "/about/", name = "About", slash = true},
    {url = "/posts/", name = "Posts", slash = true},
    {url = "/categories/", name = "Categories", slash = true},
    {url = "/tags/", name = "Tags", slash = true},
]
menu_footer = [
    {url = "/", name = "Home", slash = true},
    {url = "/about/", name = "About", slash = true},
    {url = "/contact/", name = "Contact", slash = true},
    {url = "/privacy/", name = "Privacy", slash = true},
    {url = "/sitemap.xml", name = "Sitemap", slash = false},
]


#################
# Resource Files
#################
banner = "banner.png" # Used as default image for OpenGraph/Twitter if page specific image is undefined.
js_search_index ="search_index.en.js"
js_search = "search.min.js"
rss_atom_feed = "atom.xml"
stylesheet = "abridge.css" # location and file to use for stylesheet:
#       abridge.css - Automatic Dark/Light Theme based on browser/system preference.
#  abridge-dark.css - Dark Theme
# abridge-light.css - Light Theme

# For externally loaded fonts make sure the include the FULL url including the http/https prefix
fonts_load = false
fonts = [
    {url = "https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700|Source+Code+Pro"},
    {url = "https://fonts.googleapis.com/css?family=Merriweather:300,400|Montserrat:400,700"},
    {url = "font/FiraCode-Bold.woff2"},
    {url = "font/FiraCode-Regular.woff2"},
]

# favicons, comment out a line to disable loading some or all of these.
favicon_theme_color = "#333333"
favicon_ms_color = "#333333"
favicon_webmanifest = "site.webmanifest" # Used for android-chrome-512x512.png and android-chrome-192x192.png
favicon_mask = "safari-pinned-tab.svg" # safari-pinned-tab.svg
favicon_mask_color = "#ff9900"
favicon180 = "apple-touch-icon.png" # apple-touch-icon.png
favicon32 = "favicon-32x32.png" # favicon-32x32.png
favicon16 = "favicon-16x16.png" # favicon-16x16.png

katex_enable = false # used to to render mathematical notations, requires js
katex_auto_render = false

##########################
# meta/seo/analytic tags
##########################
keywords = "Whatever, SEO, keywords, you want" # used for the primary site index
twitter = "your-user-name" # used for twitter related
#google = "Your Google Site verification code."
#bing = "Your Bing Site verification code."
seo = true  # enable or disable seo-related meta tags: opengraph, facebook, twitter

# Footer social links; full options listed in macros/social.html
[extra.social]
feed = true
mail = "name@example.com"
mastodon = "@your-user-name"
element = "matrix.example.com"
#matrix = "matrix.example.com"
buymeacoffee = "your-user-name"
twitter = "your-user-name"
facebook = "your-user-name"
linkedin = "your-user-name"
gitlab = "your-user-name"
github = "your-user-name"
github_sponsor = "your-user-name"
bitbucket = "your-user-name"
python = "your-user-name"
docker = "your-user-name"
stack = "your-user-name"
instagram = "your-user-name"
pinterest = "your-user-name"
twitch = "your-user-name"
youtube = "your-channel-id"

