name = "abridge"
description = "A fast and lightweight Zola theme using semantic html, a class-light abridge.css, and No JS."
license = "MIT"
homepage = "https://github.com/jieiku/abridge/"
min_version = "0.16.1"
demo = "https://abridge.netlify.app/"

[extra]

[author]
name = "Jake G (jieiku)"
homepage = "https://github.com/jieiku/"
