name = "abridge"
description = "A fast and lightweight Zola theme using semantic html, a class-light abridge.css, and No mandatory JS."
license = "MIT"
homepage = "https://github.com/jieiku/abridge"
min_version = "0.17.2"
demo = "https://abridge.netlify.app/"

# Abridge theme author info
[author]
name = "Jake G (jieiku)"
homepage = "https://github.com/jieiku/"

[extra]
